/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: ["index",
  {
    type: 'category',
    label: 'Modules',
    link: {
      type: 'doc',
      id: 'modules/index',
    },
    collapsed: true,
    items: [
      "modules/verification",
      "modules/logging",
      "modules/points",
      "modules/rewards",
      "modules/roles",
      "modules/automod",
      "modules/moderation",


    ],
  },
  {
    type: 'category',
    label: 'Commands',
    link: {
      type: 'generated-index',
      title: "Commands",
      slug: "/commands",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'commands',
      },
    ],
  },
  {
    type: 'category',
    label: 'Guides',
    link: {
      type: 'generated-index',
      title: "Guides",
      slug: "/guides",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'guides',
      },
    ],
  },
  {
    type: 'category',
    label: 'Developer',
    link: {
      type: 'generated-index',
      title: "Developer",
      slug: "/developer",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'developer',
      },
    ],
  },
  {
    type: 'category',
    label: 'Simpukka',
    link: {
      type: 'generated-index',
      title: "Simpukka",
      slug: "/simpukka",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'simpukka',
      },
    ],
  },

  ],





};

export default sidebars;
