/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: ["index",
  {
    type: 'category',
    label: 'Modules',
    link: {
      type: 'doc',
      id: 'modules/index',
    },
    collapsed: true,
    items: [
      "modules/verification",
      "modules/logging",
      "modules/points",
      "modules/rewards",
      "modules/roles",
      "modules/automod",
      "modules/moderation",
      "modules/anti-bot",


    ],
  },
  {
    type: 'category',
    label: 'Commands',
    link: {
      type: 'doc',
      id: 'commands/index',
    },
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'Slash',
        link: {
          type: 'doc',
          id: 'commands/slash/index',
        },
        items: [
          'commands/slash/test',
          'commands/slash/point-module-commands',

        ],
      },
      {
        type: 'category',
        label: 'Prefix',
        link: {
          type: 'doc',
          id: 'commands/prefix/index',
        },
        items: [
          'commands/prefix/test',

        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'Guides',
    link: {
      type: 'generated-index',
      title: "Guides",
      slug: "/guides",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'guides',
      },
    ],
  },
  {
    type: 'category',
    label: 'Developer',
    link: {
      type: 'generated-index',
      title: "Developer",
      slug: "/developer",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'developer',
      },
    ],
  },
  {
    type: 'category',
    label: 'Simpukka',
    link: {
      type: 'generated-index',
      title: "Simpukka",
      slug: "/simpukka",
    },
    collapsed: true,
    items: [
      {
        type: 'autogenerated',
        dirName: 'simpukka',
      },
    ],
  },
  "localisation",
  ],





};

export default sidebars;
